In [1]:
import numpy as np
import matplotlib.pyplot as plt

#Create a 3*3 matrix of random integer between 1 and 50

random_matrix = np.random.randint(1, 50, (3, 3))

print(random_matrix)


[[18  4 19]
 [39 24 46]
 [30 48 14]]


In [5]:
#Create a 3*3 matrix of random integer with a fixed seed

np.random.seed(10)
random_matrix = np.random.randint(1, 50, (3, 3))

print(random_matrix)

[[36 15 48]
 [39 17 10]
 [ 9 37 40]]


In [10]:
# Create a 3*3 matrix of random integers between 1 and 50 integer without fixed seed

without_seed_random_matrix = np.random.randint(1, 50, (3, 3))

print(without_seed_random_matrix)

[[32  3  5]
 [39 42 20]
 [20 19  8]]


Explaination:

Question 1 - Create a 3×3 matrix of random integers without fixed output .The output will different from every time run this code.

Question 2 - Create a 3×3 matrix of random integers with a fixed seed (10).By using the seed,the output will same sequence of random numbers are fixed in the fist running code.

Question 3 - Same as Question-1 ,generates another random integers without seed.



